config/routes.rb
Rails.application.routes.draw do
  get 'posts/create'
  get 'posts/edit'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'static_pages#home'
  # get "/about", to: "static_pages#about"
  devise_for :users, controllers: { confirmations: 'confirmations' }
  resources :dashboard, only: [:index, :edit]
  resources :posts, only: [:new, :create, :edit, :update, :destroy]
  resources :search, only: [:index, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord

  has_many :posts, dependent: :destroy

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :avatar

  # protected
  # def confirmation_required?
  #   false
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include Pagy::Backend

    before_action :configure_permitted_parameters, if: :devise_controller?

    # Devise config
    protected

    def configure_permitted_parameters
        # devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
        devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
    end


    def after_sign_in_path_for(resource)
        dashboard_index_path
    end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController

    #Devise configs
    protected
    def after_confirmation_path_for(resource_name, resource)
      sign_in(resource)
      dashboard_index_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    before_action :set_user, only: [:edit]

    def index
        @pagy, @posts = pagy(current_user.posts.order("posts.created_at DESC"), items: 6, size: [1,1,1,1])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:edit, :update, :show, :destroy]

  def new
    @post = Post.new
  end

  def create
    # @post = Post.new(post_params)
    # @post.user_id = current_user.id
    # Refactor
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to dashboard_index_path, notice: "Post was successfully created."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to dashboard_index_path, notice: "Your post was successfully updated!"
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to dashboard_index_path, notice: "Post successfully deleted."
  end

  private

  def set_post
    @post = current_user.posts.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    before_action :set_post, only: [:show]

    def index
        @pagy, @posts = pagy(Post.all.order("posts.created_at DESC"), items: 8, size: [1,1,1,1])
    end

    def show
        
    end


    private

    def set_post
        @post = Post.find(params[:id])
    end
    
    def search_params
        
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    include Pagy::Frontend

    def nav_link(text, path, method)
        if current_page?(path)
             content_tag(:li, class: "nav-items mx-2 active") do
                 link_to(path, class: "nav-link text-info bold", method: method) do
                     sanitize(text) + content_tag(:span, "(current)", class: "sr-only")
                 end
             end
         else
             content_tag(:li, class: "nav-items mx-2") do
                 link_to(text, path, class: "nav-link", method: method)
             end
        end   
    end


    def chop_email(email)
        return email.split("@")[0]
    end
    
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/dashboard/index.html.erb
<%# Show message if user is unverified %>
<% if !current_user.confirmed_at %>
  <div class="alert alert-info alert-dismissible fade show" role="alert">
    Your account is not verified. Confirm your email within 
    <%# Calculating time left to verify account %>
    <%= distance_of_time_in_words(current_user.created_at, User.allow_unconfirmed_access_for.from_now) %>.
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

<div class="flex justify-content-between align-items-center flex-wrap">
    <h2>Dashboard</h2>
    
    <div class="flex flex-column align-items-center">
        <%= image_tag 'new_user', class: "rounded-circle border border-info", style: "height:60px; width:60px; object-fit:cover" %>
    
         <div class="dropdown">
          <div type="button" class="dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="text-muted"><%= current_user.email %></span>
                <span class="sr-only">Toggle Dropdown</span>
          </div>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
            <%= nav_link "Edit Account", edit_user_registration_path , :get %>
            <%= nav_link "Booking History", root_path, :get %>
            <%= nav_link "Logout", destroy_user_session_path, :delete %>
          </div>
        </div>
    </div>
</div>


<div class="mt-5 mb-5">
    <h5 class="text-success">You have <%= pluralize(@pagy.count, " active post") %></h5>
    <h6 class="text-info"><%= pluralize(@posts.count, " active post") %> in this page</h6>
</div>

<% if @posts.any? %>        
    <%= link_to "Create new post", new_post_path, class: "btn btn-success" %>

    <div class="mt-5 mb-5">
      <h2>Your Posts</h2>
      <% @posts.each do |post| %>
        <%= render partial: 'posts/post_card', locals: {post: post }%>
      <% end %>
    </div>
<% else %>
    <div class="card mt-3 mb-3">
      <div class="container m-4">
          <h3>There are not posts to show.</h3>
          <p>Get started by creating your very first listing.</p>
      </div>
      <%= link_to "Create new post", new_post_path, class: "btn btn-success" %> 
    </div>
<% end %>

<div class="container flex justify-content-center">
  <%== render partial: 'pagy/bootstrap_nav', locals: {pagy: @pagy} if @pagy.pages > 7 %>
</div>


app/views/layouts/_footer.html.erb
<!-- Footer -->
<footer class="page-footer font-small blue-grey lighten-5 text-white" style="background-color: #1c2331">

  <div style="background-color: #6351ce;">
    <div class="container">

      <!-- Grid row-->
      <div class="row py-4 d-flex align-items-center">

        <!-- Grid column -->
        <div class="col-md-6 col-lg-5 text-center text-md-left mb-4 mb-md-0">
          <h6 class="mb-0 text-white">Get connected with us on social networks!</h6>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-6 col-lg-7 text-center text-md-right">

          <!-- Facebook -->
          <a href="facebook.com" target="blank" class="fb-ic">
            <i class="fab fa-facebook-f mr-4 text-white"></i>
          </a>
          <!-- Twitter -->
          <a href="" class="tw-ic">
            <i class="fab fa-twitter mr-4 text-white"></i>
          </a>
          <!--Linkedin -->
          <a href="" class="li-ic">
            <i class="fab fa-linkedin-in mr-4 text-white"></i>
          </a>
          <!--Instagram-->
          <a href="" class="ins-ic">
            <i class="fab fa-instagram text-white"></i>
          </a>

        </div>
        <!-- Grid column -->

      </div>
      <!-- Grid row-->

    </div>
  </div>

  <!-- Footer Links -->
  <div class="container text-center text-md-left mt-5">

    <!-- Grid row -->
    <div class="row mt-3 dark-grey-text">

      <!-- Grid column -->
      <div class="col-md-3 col-lg-4 col-xl-3 mb-4">

        <!-- Content -->
        <h6 class="text-uppercase font-weight-bold border-bottom border-info">DoGGo Inc.</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>Awesome community of DoGGo's, DoGGo-owners and DoGGo-caregivers</p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold border-bottom border-info">Services</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="text-white" href="#!">DoGGo Roamer</a>
        </p>
        <p>
          <a class="text-white" href="#!">DoGGo Sitter</a>
        </p>
        <p>
          <a class="text-white" href="#!">DoGGo Cleaner</a>
        </p>
        <p>
          <a class="text-white" href="#!">FAQ</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold border-bottom border-info">Careers</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <a class="text-white" href="#!">Your Account</a>
        </p>
        <p>
          <a class="text-white" href="#!">Become an Affiliate</a>
        </p>
        <p>
          <a class="text-white" href="#!">Careers @ DoGGo</a>
        </p>
        <p>
          <a class="text-white" href="#!">Help</a>
        </p>

      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">

        <!-- Links -->
        <h6 class="text-uppercase font-weight-bold border-bottom border-info">Contact</h6>
        <hr class="teal accent-3 mb-4 mt-0 d-inline-block mx-auto" style="width: 60px;">
        <p>
          <i class="fas fa-home mr-3"></i> New York, NY 10012, US</p>
        <p>
          <i class="fas fa-envelope mr-3"></i> info@doggo.com</p>
        <p>
          <i class="fas fa-phone mr-3"></i> + 01 234 567 88</p>
        <p>
          <i class="fas fa-print mr-3"></i> + 01 234 567 89</p>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

    <div class="container">
      <%= image_tag 'google-play-badge.png', class: "img-fluid", style: "width:150px;" %>
      <%= image_tag 'apple-store-badge.svg', class: "img-fluid", style: "width:120px;" %>
    </div>

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center text-white-50 py-3">© 2020 DoGGo™ : by
    <a class="text-white" target="_blank" href="https://tihang.github.io"> Tihang Rai</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->


app/views/layouts/_navbar.html.erb

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand text-info bold ml-1" href="/">
   <%= image_tag 'favicon.png', style: "height:70px; width:70px; object-fit:cover;" %> DoGGo
  </a>
  <button class="hamburger hamburger--3dx navbar-toggler shadow-sm" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation" style="outline:none;">
    <span class="hamburger-box">
    <span class="hamburger-inner"></span>
  </span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <%= nav_link "Home", root_path, :get %>
      <%# <%= nav_link "About", about_path, :get %>
      <%= nav_link "Search", search_index_path, :get %>
    </ul>

    <ul class="nav navbar-nav ml-auto">
      <% if !user_signed_in? %>
        <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary m-2" %>
        <%= link_to "Sign in", new_user_session_path, class: "btn btn-info m-2" %>
      <% else %>
        <%= nav_link "Dashboard", dashboard_index_path, :get %>
        <%= nav_link "Logout", destroy_user_session_path, :delete %>
      <% end %>
    </ul>
  </div>

</nav>

app/views/layouts/_notification.html.erb
<% if notice %>
    <div class="alert alert-info mb-0" role="alert"><p class="notice"><%= notice %></p></div>
<% end %>
<% if alert %>
    <div class="alert alert-danger mb-0" role="alert"><p class="alert"><%= alert %></p></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoGGo</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('favicon.png') %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/fontawesome.min.css" integrity="sha256-mM6GZq066j2vkC2ojeFbLCcjVzpsrzyMVUnRnEQ5lGw=" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/brands.min.css" integrity="sha256-G2I5BfHSSC9AXQyjI9B2w0Fue6RdgGpTAt3m2Zmzw04=" crossorigin="anonymous" />
    <link href="https://unpkg.com/basscss@8.0.2/css/basscss.min.css" rel="stylesheet">
  </head>

  <body>

  <%= render 'layouts/notification' %>
  <%= render 'layouts/navbar' %> 

    <div class="container mt-5 mb-5" style="min-height:68vh;">
      <%= yield %>
    </div>

  <%= render 'layouts/footer' %>
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/js/all.min.js" integrity="sha256-MAgcygDRahs+F/Nk5Vz387whB4kSK9NXlDN3w58LLq0=" crossorigin="anonymous"></script>
    <script>
      $(document).ready(function() {
        // Check for click events on the navbar burger icon
        $(".navbar-burger").click(function() {
            // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
            $(".navbar-burger").toggleClass("is-active");
            $(".navbar-menu").toggleClass("is-active");
        });
      });
      
      // Fire up bootstrap tooltip
      $(function () {
        $('[data-toggle="tooltip"]').tooltip()
      });

      // Hamburger menu animation helper
      var $hamburger = $(".hamburger");
        $hamburger.on("click", function(e) {
          $hamburger.toggleClass("is-active");
        });


      // // Typewriter effect JS
      //   var TxtType = function(el, toRotate, period) {
      //   this.toRotate = toRotate;
      //   this.el = el;
      //   this.loopNum = 0;
      //   this.period = parseInt(period, 10) || 2000;
      //   this.txt = '';
      //   this.tick();
      //   this.isDeleting = false;
      // };

      // TxtType.prototype.tick = function() {
      //     var i = this.loopNum % this.toRotate.length;
      //     var fullTxt = this.toRotate[i];

      //     if (this.isDeleting) {
      //     this.txt = fullTxt.substring(0, this.txt.length - 1);
      //     } else {
      //     this.txt = fullTxt.substring(0, this.txt.length + 1);
      //     }

      //     this.el.innerHTML = '<span class="wrap">'+this.txt+'</span>';

      //     var that = this;
      //     var delta = 200 - Math.random() * 100;

      //     if (this.isDeleting) { delta /= 2; }

      //     if (!this.isDeleting && this.txt === fullTxt) {
      //     delta = this.period;
      //     this.isDeleting = true;
      //     } else if (this.isDeleting && this.txt === '') {
      //     this.isDeleting = false;
      //     this.loopNum++;
      //     delta = 500;
      //     }

      //     setTimeout(function() {
      //     that.tick();
      //     }, delta);
      // };

      // window.onload = function() {
      //     var elements = document.getElementsByClassName('typewrite');
      //     for (var i=0; i<elements.length; i++) {
      //         var toRotate = elements[i].getAttribute('data-type');
      //         var period = elements[i].getAttribute('data-period');
      //         if (toRotate) {
      //           new TxtType(elements[i], JSON.parse(toRotate), period);
      //         }
      //     }
      //     // INJECT CSS
      //     var css = document.createElement("style");
      //     css.type = "text/css";
      //     css.innerHTML = ".typewrite > .wrap { border-right: 0.08em solid #fff}";
      //     document.body.appendChild(css);
      // };
    </script>
  </body>
</html>

app/views/pagy/_bootstrap_nav.html.erb
<%#
  This template is i18n-ready: if you don't use i18n, then you can replace the pagy_t
  calls with the actual strings ("&lsaquo; Prev", "Next &rsaquo;", "&hellip;").

  The link variable is set to a proc that returns the link tag.
  Usage: link.call( page_number [, text [, extra_attributes_string ]])
-%>
<% link = pagy_link_proc(pagy, 'class="page-link"') -%>
<%#                            -%><nav aria-label="pager"  class="pagy-bootstrap-nav" role="navigation">
<%#                            -%>  <ul class="pagination">
<% if pagy.prev                -%>    <li class="page-item prev"><%== link.call(pagy.prev, pagy_t('pagy.nav.prev'), 'aria-label="previous"') %></li>
<% else                        -%>    <li class="page-item prev disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.prev') %></a></li>
<% end                         -%>
<% pagy.series.each do |item| # series example: [1, :gap, 7, 8, "9", 10, 11, :gap, 36] -%>
<%   if    item.is_a?(Integer) -%>    <li class="page-item"><%== link.call(item) %></li>
<%   elsif item.is_a?(String)  -%>    <li class="page-item active"><%== link.call(item) %></li>
<%   elsif item == :gap        -%>    <li class="page-item disabled gap"><a href="#" class="page-link"><%== pagy_t('pagy.nav.gap') %></a></li>
<%   end                       -%>
<% end                         -%>
<% if pagy.next                -%>    <li class="page-item next"><%== link.call(pagy.next, pagy_t('pagy.nav.next'), 'aria-label="next"') %></li>
<% else                        -%>    <li class="page-item next disabled"><a href="#" class="page-link"><%== pagy_t('pagy.nav.next') %></a></li>
<% end                         -%>
<%#                            -%>  </ul>
<%#                            -%></nav>

app/views/posts/_post_card.html.erb

<div class="shadow-sm card mt-3 mb-3" style="width: 100%;">   
  <div class="card-body">
    <div class="container-fluid">
      <div class="flex justify-content-between">
        <div class="flex align-self-center">
          <%# User avatar %>
          <%= image_tag 'new_user', class: "shadow rounded-circle border border-info mb-3 mr-3", style: "height:30px; width:30px; object-fit:cover;" %>
          <%# Username %>
          <span class="text-muted"><%= chop_email(post.user.email) %> 
            <%# Verified checkmark or unverfied mark %>
            <% if post.user.confirmed_at %>
              <i class="text-success far fa-check-circle" data-toggle="tooltip" data-placement="top" title="Verified"></i>
            <% else %>
              <i class="text-warning fas fa-exclamation-circle" data-toggle="tooltip" data-placement="top" title="Confirm email to get verified"></i>
            <% end %>
          </span>
        </div>
          <%# Only allow edit and delete actions if post belongs to user %>
          <% if user_signed_in? && current_user.id === post.user_id %>
            <div class="flex">
              <%# Edit link %>
              <%= link_to edit_post_path(post), class: "flex flex-column align-items-center" do %>
                <i class="far fa-edit text-info ml-4 mr-4"></i>
                <p class="text-muted">Edit</p>
              <% end %>
              <%# Delete link %>
              <%= link_to post_path(post), method: :delete, data: { confirm: "Are you sure?"}, class: "flex flex-column align-items-center" do %>
                <i class="far fa-trash-alt text-danger ml-4 mr-4"></i>
                <p class="text-muted">Delete</p>
              <% end %>    
            </div>
          <% end %>

      </div>
      <%= link_to search_path(post), class: "text-info" do %>
        <h5 class="card-title"><%= post.title %></h5>
      <% end %>
      <%# <p class="card-text"><%= post.body %></p> 
    </div>

    <div class="container flex justify-content-between flex-wrap mt-3">
      <div class="flex flex-column align-items-center">
        <%# Like button %>
        <%= link_to search_path(post) do %>
          <span class="text-lg text-muted">
            <%= post.likes %>
              <i class="far fa-comment-dots"></i>
          </span>
        <% end %>
      </div>
      
      <%# Timestamp %>
      <p class="text-muted"><%= time_ago_in_words(post.created_at) %> ago</p>
    </div>
  </div>
</div>

<hr>

app/views/posts/_post_form.html.erb
<%= form_with model: post, validate: true, class: "form-group" do |f| %>
    <div class="mb-5 mt-3">
        <%= link_to dashboard_index_path, class: "text-info" do %>
            <i class="fas fa-arrow-left"></i> Back
        <% end %>
    </div>

    <div class="form-group">
        <%= f.label :title, "Title: " %>
        <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group">
        <%= f.label :body, "Description: " %>
        <%= f.text_area :body, class: "form-control", rows: 8 %>
    </div>

<%= f.submit class: "btn btn-success" %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render partial: 'posts/post_form', locals: { post: @post } %>

app/views/posts/new.html.erb
<h1>Create new post</h1>

<%= render partial: 'posts/post_form', locals: { post: @post } %>

app/views/search/index.html.erb
<h2>Search</h2>


<h5 class="text-success">We have a total of <%= pluralize(@pagy.count, "listing") %></h5>
<h6 class="text-info"><%= pluralize(@posts.count, "listing") %> on this page</h6>

<div class="container mt-5 mb-5">

    <div class="container flex justify-content-center">
        <%== render partial: 'pagy/bootstrap_nav', locals: {pagy: @pagy} if @pagy.pages > 7%>
    </div>
        
    <% @posts.each do |post| %>
        <%= render partial: 'posts/post_card', locals: { post: post } %>
    <% end %>

    <div class="container flex justify-content-center">
        <%== render partial: 'pagy/bootstrap_nav', locals: {pagy: @pagy} if @pagy.pages > 7%>
    </div>

</div>

app/views/search/show.html.erb
<div class="mt-5 mb-4">
    <%= link_to :back, class: "text-info" do %>
        <i class="fas fa-arrow-left"></i> Back
    <% end %>
</div>
<h1>Details:</h1>

<div class="container mt-4">
    <h4 class="mt-4 mb-4"><%= @post.title %></h4>
    <p><%= @post.body %></p>
</div>

<div>
    <%= render partial: 'posts/comments/comments_card' %>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron shadow mt-5 mb-5 flex flex-column justify-content-end" style="background-image:url(<%= asset_path('jumbotron_dog3.jfif') %> ); background-position: 50% 17%; height:400px">
  <h1 class="text-white flex justify-content-center align-items-end font-weight-bold">DoGGo</h1>
  <div class="flex justify-content-center align-items-end">
    <%= link_to "Start search", search_index_url, class:"btn btn-info btn-lg" %>
  </div>
</div>


<div class="jumbotron shadow" style="background-image:linear-gradient(141deg,#009e6c 0,#00d1b2 71%,#00e7eb 100%);">
  <div class="container pl-5">
    <h1 class="display-5 text-white">DoGGo</h1>
    <p class="lead text-white">Your Dog on the Go..</p>
    <p class="text-white">Try Doggo today.</p>
    <%= link_to  "Sign up", new_user_registration_path, class:"btn btn-dark btn-lg" %>
  </div>
</div>



<div class="container">
    <div class="row">
        <div class="col-lg-3 col-md-4 col-sm-12 card mx-auto text-center shadow-sm mb-3 mt-3">
            <%= image_tag 'illustrations/undraw_good_doggy', class: "card-img-top pt-3" %>
            <div class="card-body">
                <h5 class="card-title">Care giving like never before</h5>
                <p class="card-text">Our DoGGo professionals know whats best for your pet. Your pets are in good hands.</p>
            </div>
            <div class="flex align-items-end justify-content-center mb-4">
              <%= link_to "Learn more", search_index_path, class: "btn btn-info btn-block" %>
            </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-12 card mx-auto text-center shadow-sm mb-3 mt-3">
            <%= image_tag 'illustrations/undraw_dog_walking', class: "card-img-top pt-3" %>
            <div class="card-body">
                <h5 class="card-title">Fit your schedule</h5>
                <p class="card-text">Find and schedule with your pet with a DoGGo-caregive. Find the service your pet deserves. </p>
            </div>
            <div class="flex align-items-end justify-content-center mb-4">
              <%= link_to "Schedule options", dashboard_index_path, class: "btn btn-info btn-block" %>
            </div>
        </div>

        <div class="col-lg-3 col-md-4 col-sm-12 card mx-auto text-center shadow-sm mb-3 mt-3">
            <%= image_tag 'illustrations/undraw_team_spirit', class: "card-img-top pt-3" %>
            <div class="card-body">
                <h5 class="card-title">Awesome community</h5>
                <p class="card-text">Connect with awesome DoGGo professionals as well as DoGGo owners.</p>
            </div>
            <div class="flex align-items-end justify-content-center mb-4">
              <%= link_to "Go somewhere", dashboard_index_path, class: "btn btn-info btn-block" %>
            </div>
        </div>
    </div>
</div>